import { app, ipcMain, webContents } from 'electron';
import { writeFileSync } from 'fs';
import { join } from 'path';
import { IPC } from '@shared/ipc';
import type { BrowserClock } from '@shared/types';

// Fake clock for the browser panel, so a page's JavaScript can be shown any
// date and time without touching the system clock. Every webview gets a tiny
// preload that swaps the page's Date for one reading from an offset. CDP's
// virtual time would be the obvious tool, but netlog already holds the
// webview's debugger — and a preload runs before the page's first script,
// which is what makes `new Date()` at the top of a bundle see the fake time.

/** Wall-clock time the page should see, anchored to a real moment. */
type ClockState = { at: number; setAt: number; frozen: boolean } | null;
let clock: ClockState = null;

/** What a shim needs: real-time offset, or a fixed instant when frozen. */
function shimState(): { offset: number; frozenAt: number | null } {
  if (!clock) return { offset: 0, frozenAt: null };
  if (clock.frozen) return { offset: 0, frozenAt: clock.at };
  return { offset: clock.at - clock.setAt, frozenAt: null };
}

function describe(): BrowserClock {
  if (!clock) return { fake: false, now: Date.now(), frozen: false };
  const s = shimState();
  return { fake: true, now: s.frozenAt ?? Date.now() + s.offset, frozen: clock.frozen };
}

// Runs in the page's own world. Installed on every page, even with the real
// clock in effect (offset 0), so a later change can apply live without a
// reload. State lives on a non-enumerable window slot that only the host's
// update script writes.
const SHIM = String.raw`(function (init) {
  if (window.__odClock) { window.__odClock.offset = init.offset; window.__odClock.frozenAt = init.frozenAt; return; }
  const state = { offset: init.offset, frozenAt: init.frozenAt };
  Object.defineProperty(window, '__odClock', { value: state, enumerable: false });
  const RealDate = Date;
  const realNow = RealDate.now.bind(RealDate);
  const now = () => (state.frozenAt != null ? state.frozenAt : realNow() + state.offset);
  function FakeDate(...args) {
    if (!new.target) return new RealDate(now()).toString();
    return Reflect.construct(RealDate, args.length ? args : [now()], new.target);
  }
  Object.defineProperty(FakeDate, 'length', { value: 7 });
  Object.defineProperty(FakeDate, 'name', { value: 'Date' });
  FakeDate.prototype = RealDate.prototype;
  Object.defineProperty(RealDate.prototype, 'constructor', { value: FakeDate, writable: true, configurable: true });
  FakeDate.now = function now_() { return now(); };
  FakeDate.parse = RealDate.parse;
  FakeDate.UTC = RealDate.UTC;
  // Keep feature sniffing ("is Date native?") from noticing the swap.
  const nativeToString = Function.prototype.toString;
  const disguised = new Map([[FakeDate, nativeToString.call(RealDate)], [FakeDate.now, nativeToString.call(RealDate.now)]]);
  Function.prototype.toString = function toString() {
    return disguised.has(this) ? disguised.get(this) : nativeToString.call(this);
  };
  disguised.set(Function.prototype.toString, nativeToString.call(nativeToString));
  window.Date = FakeDate;
  // Intl formats "now" from the engine's clock, not Date, when no date is given.
  const dtf = Intl.DateTimeFormat.prototype;
  const fmt = Object.getOwnPropertyDescriptor(dtf, 'format');
  if (fmt && fmt.get) {
    Object.defineProperty(dtf, 'format', { configurable: true, get() {
      const f = fmt.get.call(this);
      return (d) => f(d === undefined ? now() : d);
    } });
  }
  const parts = dtf.formatToParts;
  dtf.formatToParts = function formatToParts(d) { return parts.call(this, d === undefined ? now() : d); };
})`;

const PRELOAD = `// Generated by openDev (browserClock.ts). Installs the browser panel's fake clock.
const { ipcRenderer, webFrame } = require('electron');
let init = { offset: 0, frozenAt: null };
try { init = ipcRenderer.sendSync(${JSON.stringify(IPC.BrowserClockSync)}) || init; } catch {}
webFrame.executeJavaScript(${JSON.stringify(SHIM)} + '(' + JSON.stringify(init) + ')');
`;

let preloadPath: string | null = null;

/** The preload is written out at startup rather than bundled: it has to be a
 *  plain CommonJS file, since webviews run sandboxed and can't load the ESM
 *  build the IDE's own preload uses. */
function ensurePreload(): string | null {
  if (preloadPath) return preloadPath;
  try {
    const file = join(app.getPath('userData'), 'webview-clock-preload.cjs');
    writeFileSync(file, PRELOAD);
    preloadPath = file;
  } catch (err: any) {
    console.log('[browserClock] could not write preload:', err?.message || err);
  }
  return preloadPath;
}

/** Push the current clock into every frame of every live webview. */
function applyLive(): void {
  const script = `${SHIM}(${JSON.stringify(shimState())})`;
  for (const wc of webContents.getAllWebContents()) {
    if (wc.getType() !== 'webview' || wc.isDestroyed()) continue;
    for (const frame of wc.mainFrame.framesInSubtree) {
      frame.executeJavaScript(script).catch(() => { /* cross-origin or mid-teardown */ });
    }
  }
}

export function registerBrowserClockIpc(): void {
  // Any window that hosts a <webview> (the IDE and its pop-outs).
  app.on('web-contents-created', (_e, contents) => {
    contents.on('will-attach-webview', (_ev, prefs) => {
      const file = ensurePreload();
      if (!file) return;
      prefs.preload = file;
      // Same-origin iframes have their own Date; the preload has to run there too.
      prefs.nodeIntegrationInSubFrames = true;
    });
  });

  ipcMain.on(IPC.BrowserClockSync, (e) => { e.returnValue = shimState(); });

  ipcMain.handle(IPC.BrowserClockGet, (): BrowserClock => describe());

  ipcMain.handle(IPC.BrowserClockSet, (_e, opts: { at: number; frozen: boolean } | null): BrowserClock => {
    clock = opts && Number.isFinite(opts.at)
      ? { at: opts.at, setAt: Date.now(), frozen: !!opts.frozen }
      : null;
    applyLive();
    return describe();
  });
}
